### ISSUE TITLE
✨  전화번호로도 센터 검색할 수 있게 수정

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/BE_POLICE_LEGACY_PUBLIC#50]
## 📌 Feature Issue
- 전화번호로 센터를 검색할 수 있다.

## 📝 To-do
- [x] 센터 검색 API에 전화번호로 검색하는 로직 추가
- [x] 관련 테스트코드 수정

**Comment by uwoobeat** [comment]
이미 구현된 기능이니 확인 부탁드립니다~
해당 이슈는 닫도록 하겠습니다
